panoplic/companies/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views

segments = [
    url(
        r'^homes/$',
        TemplateView.as_view(template_name='segments/homes.html'),
        name='homes'
    ),
    url(
        r'^businesses/$',
        TemplateView.as_view(template_name='segments/businesses.html'),
        name='businesses'
    ),
    url(
        r'^vehicles/$',
        TemplateView.as_view(template_name='segments/vehicles.html'),
        name='vehicles'
    ),
    url(
        r'^enterprises/$',
        TemplateView.as_view(template_name='segments/enterprises.html'),
        name='enterprises'
    ),
]

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^segments/', include(segments, namespace='segments')),
    url(
        r'^terms-conditions/$',
        TemplateView.as_view(template_name='terms.html'),
        name='terms-conditions'
    ),
    url(
        r'^how-to-publish/$',
        TemplateView.as_view(template_name='howto_publish.html'),
        name='how-to-publish'
    ),
    url(
        r'^how-to-register/$',
        TemplateView.as_view(template_name='howto_register.html'),
        name='how-to-register'
    ),
    url(
        r'^how-it-works/$',
        TemplateView.as_view(template_name='how_works.html'),
        name='how-it-works'
    ),
    url(
        r'^scope/$',
        TemplateView.as_view(template_name='scope.html'),
        name='scope'
    ),
    url(
        r'^contact/$',
        TemplateView.as_view(template_name='contact.html'),
        name='contact'
    ),
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^403/$', TemplateView.as_view(template_name='403.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),
    url(
        r'^companies/$',
        views.CompanyListView.as_view(),
        name='companies'
    ),
    url(
        r'^company/register$',
        views.company_register,
        name='company_register'
    ),
    url(
        r'^company/success$',
        TemplateView.as_view(template_name='company_success.html'),
        name='company_success'
    ),
    url(
        r'^company/(?P<pk>\d+)/(?P<slug>[\w-]+)/$',
        views.CompanyView.as_view(),
        name='company_view'
    ),
    url(
        r'^company/profile$',
        views.company_profile,
        name='company_profile'
    ),
    url(
        r'^upload_logo/$',
        views.upload_logo,
        name='upload_logo'
    ),
    url(
        r'^delete_logo/$',
        views.delete_logo,
        name='delete_logo'
    ),
    url(r'^populate-select/$', views.populate_select),
]

panoplic/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^profile/(?P<pk>\d+)/$',
        views.ProfileView.as_view(),
        name='profile'
    ),
    url(
        r'^profile/edit/$',
        views.profile_edit,
        name='edit_profile'
    ),
    url(
        r'^upload_avatar/$',
        views.upload_avatar,
        name='upload_avatar'
    ),
    url(
        r'^delete_avatar/$',
        views.delete_avatar,
        name='delete_avatar'
    ),
    url(
        r'^favorite/(?P<id>\d+)/$',
        views.favorite,
        name='favorite'
    ),
    url(
        r'^unfavorite/(?P<id>\d+)/$',
        views.unfavorite,
        name='unfavorite'
    ),
    url(
        r'^save_search/$',
        views.save_search,
        name='save_search'
    ),
    url(
        r'^remove_search/(?P<id>\d+)/$',
        views.remove_search,
        name='remove_search'
    ),
]

panoplic/companies/models.py
import os

from django.conf import settings
from django.core.validators import MinValueValidator
from django.contrib.sites.models import Site
from django.contrib.sites.requests import RequestSite
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Avg
from django.template.loader import render_to_string
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager

from panoplic.storage import OverwriteStorage
from reviews.models import Review
from .manager import CompanyManager


class Country(models.Model):

    name = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=2, unique=True)

    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')

    def __str__(self):
        return self.name


class Province(models.Model):

    name = models.CharField(max_length=50)
    country = models.ForeignKey(Country)

    class Meta:
        verbose_name = _('Province')
        verbose_name_plural = _('Provinces')

    def __str__(self):
        return self.name


class City(models.Model):

    name = models.CharField(max_length=50)
    province = models.ForeignKey(Province)

    class Meta:
        verbose_name = _('City')
        verbose_name_plural = _('Cities')

    def __str__(self):
        return self.name


class Category(models.Model):

    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Product(models.Model):

    name = models.CharField(max_length=50, unique=True)
    code = models.SlugField(unique=True)
    category = models.ForeignKey(Category, null=True)

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.name


class Service(models.Model):

    name = models.CharField(max_length=50, unique=True)
    code = models.SlugField(unique=True)

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __str__(self):
        return self.name


class Offering(models.Model):
    company = models.ForeignKey('company')
    initial_price = models.DecimalField(
        max_digits=14,
        decimal_places=4,
        validators=[MinValueValidator(0)]
    )
    monthly_price = models.DecimalField(
        max_digits=14,
        decimal_places=4,
        validators=[MinValueValidator(0)]
    )

    class Meta:
        abstract = True


class ProductOffering(Offering):
    product = models.ForeignKey('Product')

    class Meta:
        verbose_name = _('Product Offer')
        verbose_name_plural = _('Product Offers')


class ServiceOffering(Offering):
    service = models.ForeignKey('Service')

    class Meta:
        verbose_name = _('Service Offer')
        verbose_name_plural = _('Service Offers')


@deconstructible
class CompanyImgPath(object):
    def __init__(self, suffix):
        self.suffix = suffix

    def __call__(self, instance, filename):
        return os.path.join('companies', instance.country.code,
                            slugify(instance.name) + self.suffix)


logo_path = CompanyImgPath('_logo')

comp_img1_path = CompanyImgPath('_image1')

comp_img2_path = CompanyImgPath('_image2')

comp_img3_path = CompanyImgPath('_image3')


class Company(models.Model):

    objects = CompanyManager()

    name = models.CharField(
        max_length=50, unique=True,
        verbose_name=_('Company Name')
    )
    description = models.TextField(
        max_length=250,
        blank=True,
        verbose_name=_('Description')
    )
    legal_name = models.CharField(max_length=50, verbose_name=_('Legal Name'))
    website = models.URLField(max_length=100, verbose_name=_('Website'))
    email = models.EmailField(
        max_length=255,
        verbose_name=_('email'),
        null=True
    )
    cuit = models.CharField(max_length=50, blank=True, verbose_name=_('CUIT'))
    phone = models.CharField(max_length=50, verbose_name=_('Phone'))
    address = models.CharField(max_length=50, verbose_name=_('Address'))
    address_number = models.CharField(
        max_length=50,
        verbose_name=_('Address Number')
    )
    contact_name = models.CharField(
        max_length=50,
        verbose_name=_('Contact Name'),
        blank=True
    )
    city = models.ForeignKey(City, null=True)
    province = models.ForeignKey(Province, null=True)
    country = models.ForeignKey(Country, null=True)
    products = models.ManyToManyField(Product, through='ProductOffering', blank=True)
    services = models.ManyToManyField(Service, through='ServiceOffering', blank=True)
    active = models.BooleanField(default=False)
    mark = models.FloatField(default=0.0)
    mean_rating = models.FloatField(null=True, blank=True)

    logo = models.ImageField(upload_to=logo_path,
                             default='companies/default.gif',
                             storage=OverwriteStorage())
    image1 = models.ImageField(upload_to=comp_img1_path, blank=True, null=True,
                               storage=OverwriteStorage())
    image2 = models.ImageField(upload_to=comp_img2_path, blank=True, null=True,
                               storage=OverwriteStorage())
    image3 = models.ImageField(upload_to=comp_img3_path, blank=True, null=True,
                               storage=OverwriteStorage())
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = _('Company')
        verbose_name_plural = _('Companies')
        ordering = ('-mark',)

    def send_creation_email(self, request):
        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)
        context_dict = {'company': self, 'site': site}
        message = render_to_string('email_templates/new_company.txt', context_dict)
        html_message = render_to_string('email_templates/new_company.html', context_dict)
        send_mail(
            'Nueva empresa %s' % self.name,
            message=message,
            html_message=html_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[email for name, email in settings.MANAGERS],
            fail_silently=True,
        )

    def set_mean_rating(self):
        self.mean_rating = Review.objects.filter(company=self)\
                                 .aggregate(Avg('rating'))['rating__avg']
        self.save(update_fields=['mean_rating'])
        return self.mean_rating

    def set_mark(self):
        """
        Set the current mark, returning 1 if the Company has a rating
        and 0 if it doesn't.
        """
        if not self.mean_rating:
            return 0

        PE = 10  # Weight of the prior estimate.

        global_avg = Company.objects.filter(country=self.country)\
                            .aggregate(Avg('mean_rating'))['mean_rating__avg']
        reviews = self.review_set.all()
        votes = reviews.count()
        company_avg = reviews.aggregate(Avg('net_rating'))['net_rating__avg']
        self.mark = (company_avg * votes + global_avg * PE) / (votes * PE)
        self.save(update_fields=['mark'])
        return 1

    def get_reviewers(self):
        """Return a generator of users that have reviewed the company."""
        return (review.user for review in self.review_set.all())

    def get_absolute_url(self):
        return reverse('company_view',
                       kwargs={'pk': self.pk, 'slug': slugify(self.name)})

    def __str__(self):
        return self.name

panoplic/companies/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from taggit.forms import TagField
from imagekit.forms import ProcessedImageField
from imagekit.processors import ResizeToFill

from utils.forms import validate_size, val_for
from .models import Company, Country, Province, City, ProductOffering, ServiceOffering


class CompanyForm(forms.ModelForm):

    country = forms.ModelChoiceField(
        label=_('País'),
        empty_label=_('País'),
        queryset=Country.objects.all()
    )
    province = forms.ModelChoiceField(
        label=_('Provincia'),
        empty_label=_('Provincia'),
        queryset=Province.objects.all()
    )
    city = forms.ModelChoiceField(
        label=_('Ciudad'),
        empty_label=_('Ciudad'),
        queryset=City.objects.all()
    )
    tags = TagField(required=False)
    image1 = ProcessedImageField(
        spec_id='companies:company:image1',
        processors=[ResizeToFill(320, 180, upscale=False)],
        format='JPEG',
        validators=[validate_size],
        required=False
    )
    image2 = ProcessedImageField(
        spec_id='companies:company:image2',
        processors=[ResizeToFill(320, 180, upscale=False)],
        format='JPEG',
        validators=[validate_size],
        required=False
    )
    image3 = ProcessedImageField(
        spec_id='companies:company:image3',
        processors=[ResizeToFill(320, 180, upscale=False)],
        format='JPEG',
        validators=[validate_size],
        required=False
    )
    website = forms.URLField(
        widget=forms.TextInput(attrs={'inputmode': 'url'})
    )

    def __init__(self, *args, **kw):
        super(CompanyForm, self).__init__(*args, **kw)
        country_id = val_for(self, 'country')
        self.fields['province'].queryset = Province.objects.filter(
            country__id=country_id
        ).all()
        province_id = val_for(self, 'province')
        self.fields['city'].queryset = City.objects.filter(
            province__id=province_id
        ).all()

    class Meta:
        model = Company
        fields = ('name', 'legal_name', 'website', 'email', 'description',
                  'cuit', 'phone', 'country', 'province', 'city',
                  'contact_name', 'address', 'address_number', 'logo',
                  'image1', 'image2', 'image3', 'tags')


class ProductOfferingForm(forms.ModelForm):
    class Meta:
        model = ProductOffering
        fields = ('product', 'initial_price', 'monthly_price',)


class ServiceOfferingForm(forms.ModelForm):
    class Meta:
        model = ServiceOffering
        fields = ('service', 'initial_price', 'monthly_price',)



class UploadLogoForm(forms.ModelForm):

    logo = ProcessedImageField(spec_id='compdir:company:logo',
                               processors=[ResizeToFill(100, 100)],
                               format='JPEG', validators=[validate_size])

    class Meta:
        model = Company
        fields = ('logo',)

panoplic/companies/templates/base.html
{% load i18n %}
{% load guide_extras %}
{% load staticfiles %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<html prefix="og: http://ogp.me/ns#">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% trans 'Directory of companies related to the issue of security' %}" />
    <meta property="og:title" content="{% block share_title %}Panoplic{% endblock %}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" 
        content="{% block share_img %}http://{% sitedomain %}{% static 'img/logo.jpg' %}{% endblock %}"/>
    {% comment %}
    <meta property="og:description" content="{% trans "Directory of companies related to the issue of security" %}" />
    <meta property="og:locale" content="es_AR" />
    <meta property="og:locale:alternate" content="es_ES" />
    <meta property="og:locale:alternate" content="en_GB" />
    {% endcomment %}

    <title>{% block title %}Panoplic{% endblock %}</title>
    
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" >
    <link href='http://fonts.googleapis.com/css?family=Coustard' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" >
    <link rel="stylesheet" href="{% static 'css/ui-lightness/jquery-ui.min.css' %}">
    {% block include_css_headers %}{% endblock %}

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
</head>

<body>
    {% if messages %}
    <div class="flash_msg_cont">
        <div class="flash_msg">
        {% for message in messages %}
            {{ message }}<br/>
        {% endfor %}
        </div>
    </div>
    {% endif %}

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle nav-bar-main" type="button" data-toggle="collapse"
                        data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'home' %}" class="navbar-brand">Panoplic</a>
               
                 {% if user.is_authenticated %}
                <button class="navbar-toggle nav-bar-user logueado" type="button" data-toggle="collapse" data-target="#navbar-user">
                   
                         <div class="avatar">
                                <img src="{{ MEDIA_URL }}{{ user.profile.avatar }}" class="img-circle">
                        
                        </div>  </button>
                     {% else %}
                       <button class="navbar-toggle nav-bar-user" type="button" data-toggle="collapse" data-target="#navbar-user">
                <i class="fa fa-user"></i>
                  </button>
                {% endif %}
              
            </div>
            
             <div class="navbar-collapse collapse" id="navbar-main">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">
                    Segmentos <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="themes">
                    <li><a href="{% url 'segments:homes' %}">{% trans 'Hogares' %}</a></li>
                    <li><a href="{% url 'segments:businesses' %}">{% trans 'Comercios' %}</a></li>
                    <li><a href="{% url 'segments:vehicles' %}">{% trans 'Vehículos' %}</a></li>
                    <li><a href="{% url 'segments:enterprises' %}">{% trans 'Empresas' %}</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">
                        Ayuda <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="themes">
                        <li><a href="{% url 'how-it-works' %}">{% trans 'Cómo funciona' %}</a></li>
                        <li><a href="{% url 'how-to-register' %}">{% trans 'Cómo registrarse' %}</a></li>
                        <li><a href="{% url 'scope' %}">{% trans 'Alcance de tu cuenta' %}</a></li>
                        <li><a href="{% url 'how-to-publish' %}">{% trans 'Cómo publicar tu Empresa' %}</a></li>
                    </ul>
                </li>
              </ul>       
            </div>
            
            <div class="navbar-collapse collapse" id="navbar-user">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <div class="avatar hidden-xs">

                            <a href="{% url 'profile' user.profile.pk %}">

                                <img src="{{ MEDIA_URL }}{{ user.profile.avatar }}" class="img-circle">
                            </a>
                        </div>
                        <li id="showuser"> 
                            <a href="{% url 'profile' user.profile.pk %}"><span class="hidden-xs">{{ user.username }}</span><span class="visible-xs">Mi perfil</span></a>
                        </li>
                        <li id="publicar_empresa">
                            {% if user.profile.company %}
                               <a href="{% url 'company_profile' %}">{% trans "Perfil de empresa" %}</a>
                            {% else %}
                                <a href="{% url 'company_register' %}">{% trans "Publicar empresa" %}</a>    
                            {% endif %}
                        </li>
                        <li id="logout">
                            <a href="{% url 'auth_logout' %}" class="rojo">{% trans "logout" %}</a>
                        </li>     
                    {% else %}
                        <!-- SIN AUTENTICACION -->
                        <li>
                            <a href="#" onclick="$('#login_pop').show();$('#usuario').focus();">
                                {% trans "Iniciá sesión" %}
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'registration_register' %}">
                                {% trans "Registrate " %}
                            </a>
                        </li>
                    
                        <li><a href="{% url 'company_register' %}">{% trans "Publicá tu Empresa" %}</a>
                        </li>
                    {% endif %} 
                </ul>
            </div>
        </div>
    </nav>   

    <!-- POP UP LOGIN -->
    <div id="login_pop">
        <div class="modal_body">
            <a href="#" onclick="$('#login_pop').hide()"><i id="cerrar" class="fa fa-close"></i></a>
            <h3>{% trans 'Accedé a tu cuenta' %}</h3>
            
            <p>{% trans 'Ingresá mediante tus redes sociales' %}</p>
            <ul class="social-loguin">
                <li>
                    <a href="{% url 'social:begin' 'facebook' %}"
                            class="btn btn-block btn-social btn-facebook btn-sm">
                        <i class="fa fa-facebook"></i>{% trans 'Ingresá con Facebook' %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'social:begin' 'google-oauth2' %}"
                            class="btn btn-block btn-social btn-google-plus btn-sm">
                        <i class="fa fa-google-plus"></i>{% trans 'Ingresá con Google' %}
                    </a>
                </li>
            </ul>
            <p>{% trans '...o entrá a tu cuenta de Panoplic.' %}</p>
            <form id="form_login" action="{% url 'auth_login' %}" method="POST">
                {% csrf_token %}
                <input class="form-control" type="text" id="usuario" name="username"
                    placeholder="{% trans 'Usuario' %}" />
                <input class="form-control" type="password" id="psswd" name="password"
                    placeholder="{% trans 'Contraseña' %}"/>

                <a href="{% url 'auth_password_reset' %}" class="link">{% trans 'Olvidé mi contraseña' %}</a>
                <input type="hidden" name="next" value="{{ request.path }}" id="login_next"/>

                <input type="submit" value="Entrar" class="btn btn-danger"/>
                <div id="check">
                    <input type="checkbox" id="sesion" class="form-control"/>
                    <label for="sesion" class="label_ses" >{% trans 'No cerrar sesión' %}</label>
                </div>
            </form>
            <div class="lin_az"></div>
            <label class="label_ses">
                {% trans 'Si todavía no sos usuario,' %}
                <a href="{% url 'registration_register' %}" class="link">{% trans 'Registrate ahora' %}</a>
            </label>
        </div>
    </div>

    {% block content %}{% endblock %}

    <footer id="footer">
        <section id="footer_int" class="container">
            <ul class="row">
                <li>Panoplic &reg; 2015 </li> 
                <li>| <a href="{% url 'terms-conditions' %}">{% trans ' Términos y condiciones ' %}</a> |</li>
                <li> <a href="{% url 'contact' %}">{% trans 'Contacto' %}</a> </li>   
            </ul>
        </section>   
    </footer>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/compdir-min.js' %}"></script>
    {% block include_js %}{% endblock include_js %}
</body>

</html>

panoplic/companies/templates/company_register.html
{% extends "base.html" %}
{% load i18n %}
{% load guide_extras %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}{{ block.super }} | {% trans "Registrar empresa" %}{% endblock %}

{% block content %}

<div class="body" id="registro_empresa">
    <header>
        <section class="jumbotron">
            <div class="container">
                <h2>{% trans 'Registrá' %}</h2>
                <h2 class="second_tit">tu empresa</h2>
            </div>
            <p class="subtitulo">{% trans 'Llegá a tus<span class="hidden-xs"> potenciales</span> clientes sin<span class="hidden-xs"> inversión</span><span class="visible-xs"> costo</span>' %}</p>
        </section>
    </header>

    <section class="container">
        <div class="row contenido">
            <h3 class="titulo_section col-md-7">{% trans 'Formá parte de nuestro directorio' %}</h3>
        </div>
            <div class="row contenido">
             <p class="info-section col-md-7 col-sm-7">
                   {% trans 'Si tu empresa ya aparece en Panoplic y querés asociarla a tu cuenta de usuario, envianos un e-mail a ' %} 
                    <a class="link" href="mailto:info@panoplic.com">info@panoplic.com</a>
                </p>
           </div>
            <div class="row contenido">
            <!-- columna derecha -->
            <aside id="col_der" class="col-md-4 col-sm-5 col-md-push-8 col-sm-push-7">
                <div id="info">
                    <div class="cartel">
                        <i class="fa fa-search circlefa"></i>
                        <p>{% trans '¡Fijate si tu empresa ya existe en Panoplic!' %}</p>
                        <a href="{% url 'home' %}" target="_blank">
                            <button class="btn btn-danger">{% trans 'Buscar' %}</button>
                        </a>
                    </div>
                </div>
            </aside>
            
            <article id="col_izq" class="col-line col-md-8 col-sm-7 col-md-pull-4 col-sm-pull-5"> 
                <div id="cont_form">
                    <form action="register" method="post" id="form">
                        {{ form.non_field_errors }}
                        {% csrf_token %}
                        <div class="bloque-input vertical">
                            <div class="form_line">
                                {% render_field form.name class="form-control top" placeholder="Nombre de Empresa" %}
                                {{ form.name.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.legal_name class="form-control mid" placeholder="Razón Social" %}
                                {{ form.legal_name.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.cuit class="form-control bot" placeholder="CUIT" %}
                                {{ form.cuit.errors }}
                            </div>
                        </div>
                        <div class="bloque-input vertical">
                            <div class="form_line">
                                {% render_field form.phone class="form-control top" placeholder="Teléfono" %}
                                {{ form.phone.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.website class="form-control mid" placeholder="Sitio web" %}
                                {{ form.website.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.email class="form-control bot" placeholder="E-mail" %}
                                {{ form.email.errors }}
                            </div>
                        </div>
                        <div class="bloque-input vertical">
                            <div class="form_line">
                                {% render_field form.address class="form-control top" placeholder="Calle" %}
                                {{ form.address.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.address_number class="form-control mid" placeholder="Numeración" %}
                                {{ form.address_number.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.country class="form-control mid" %}
                                {{ form.country.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.province class="form-control mid" %}
                                {{ form.province.errors }}
                            </div>
                            <div class="form_line">
                                {% render_field form.city  class="form-control mid" %}
                                {{ form.city.errors }}
                            </div>
                        </div>  
                        <div class="bloque-input vertical">
                            <label for="contact_name">{% trans 'Datos de responsable' %}</label>        
                            <input type="text" maxlength="50" name="contact_name" id="id_contact_name"  
                                placeholder="Nombre de contacto" class="form-control top">
                            {{ form.contact_name.errors }}
                        </div>
                        <br>        
                        <p class="term">
                            {% blocktrans %}
                            Una vez recibida tu solicitud, se verificará la información para corroborar la veracidad de 
                            los datos. Panoplic se reserva el derecho a no publicar la información que considere, por 
                            cualquier motivo, inadecuada.<br>
                            Al registrarte, aceptás los
                            {% endblocktrans %}
                            <a class="link" href="{% url 'terms-conditions' %}" target="_blank">
                                {% trans "Términos y Condiciones" %}
                            </a> 
                            {% trans "de Panoplic." %}
                        </p>
                        <input type="submit" value="Registrate" class="btn-danger" />
                    </form>
                </div>
            </article>
        </div>
    </section>
</div>
{% endblock %}