panoplic/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^profile/(?P<pk>\d+)/$',
        views.ProfileView.as_view(),
        name='profile'
    ),
    url(
        r'^profile/edit/$',
        views.profile_edit,
        name='edit_profile'
    ),
    url(
        r'^upload_avatar/$',
        views.upload_avatar,
        name='upload_avatar'
    ),
    url(
        r'^delete_avatar/$',
        views.delete_avatar,
        name='delete_avatar'
    ),
    url(
        r'^favorite/(?P<id>\d+)/$',
        views.favorite,
        name='favorite'
    ),
    url(
        r'^unfavorite/(?P<id>\d+)/$',
        views.unfavorite,
        name='unfavorite'
    ),
    url(
        r'^save_search/$',
        views.save_search,
        name='save_search'
    ),
    url(
        r'^remove_search/(?P<id>\d+)/$',
        views.remove_search,
        name='remove_search'
    ),
]

panoplic/users/models.py
import os

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

from panoplic.storage import OverwriteStorage
from companies.models import Company, City, Province, Country
from search.models import Search


class User(AbstractUser):
    pass


def avatar_path(instance, filename):
    return os.path.join('avatars', instance.user.username)


class UserProfile(models.Model):

    GENDER_CHOICES = (('M', _('Hombre')), ('F', _('Mujer')))

    user = models.OneToOneField(User, related_name='profile')
    city = models.ForeignKey(City, null=True)
    province = models.ForeignKey(Province, null=True)
    country = models.ForeignKey(Country, null=True)
    birthday = models.DateField(
        blank=True,
        null=True,
        verbose_name=_('Birthday')
    )
    gender = models.CharField(
        max_length=3,
        choices=GENDER_CHOICES,
        blank=True,
        verbose_name=_('Gender')
    )
    phone = models.CharField(
        max_length=50,
        blank=True,
        verbose_name=_('Phone')
    )
    favorites = models.ManyToManyField(
        Company,
        related_name='favorites',
        blank=True
    )
    searches = models.ManyToManyField(Search, blank=True)
    company = models.ForeignKey(
        Company,
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    notify_security = models.BooleanField(default=False)
    notify_video = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=avatar_path,
                               default='avatars/default.gif',
                               storage=OverwriteStorage())

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def get_rank(self):
        reviews = self.user.review_set.count()
        if reviews >= 3 and reviews < 6:
            return _("Crítico novato")
        elif reviews >= 6 and reviews < 11:
            return _("Crítico intermedio")
        elif reviews >= 11 and reviews < 21:
            return _("Crítico Avanzado")
        elif reviews >= 21 and reviews < 50:
            return _("Crítico Experto")
        elif reviews > 50:
            return _("Colaborador")

    def __str__(self):
        return self.user.username

panoplic/users/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.core.validators import MinLengthValidator
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from imagekit.forms import ProcessedImageField
from imagekit.processors import ResizeToFill
from registration.forms import RegistrationFormUniqueEmail

from utils.forms import validate_size, raw_value, val_for
from companies.models import Company, City, Province, Country
from .models import UserProfile


validate_password = MinLengthValidator(
    settings.MIN_PASSWORD_LENGTH,
    _("La contraseña debe tener al menos {} caracteres"
      .format(settings.MIN_PASSWORD_LENGTH))
)


class CustomRegistrationForm(RegistrationFormUniqueEmail):
    """
    A registration form that only requires the user to enter their e-mail
    address and password. The username is automatically generated
    This class requires django-registration to extend the
    RegistrationFormUniqueEmail
    """
    MIN_PASSWORD_LENGTH = 8

    username = forms.CharField(widget=forms.HiddenInput, required=False)
    password1 = forms.CharField(
        label=_('Contraseña'),
        widget=forms.PasswordInput,
        validators=[validate_password]
    )
    first_name = forms.CharField(label=_('Nombre'), )
    last_name = forms.CharField(label=_('Apellido'))
    country = forms.ModelChoiceField(
        label=_('País'),
        empty_label=_(u'País'),
        queryset=Country.objects.order_by('name')
    )
    province = forms.ModelChoiceField(
        label=_('Provincia'),
        empty_label=_('Provincia'),
        queryset=None
    )
    city = forms.ModelChoiceField(
        label=_('Ciudad'),
        empty_label=_('Ciudad'),
        queryset=None
    )

    def __init__(self, *args, **kw):
        super(RegistrationFormUniqueEmail, self).__init__(*args, **kw)
        self.fields.keyOrder = [
            'first_name',
            'last_name',
            'country',
            'city',
            'province',
            'email',
            'password1',
            'password2',
        ]
        self.fields['province'].queryset = Province.objects.filter(
            country__id=self.val_for('country')
        ).all()
        self.fields['city'].queryset = City.objects.filter(
            province__id=self.val_for('province')
        ).all()

    def clean(self):
        if not self.errors:
            self.cleaned_data['username'] = self.generate_username(
                self.cleaned_data['email']
            )
        super(CustomRegistrationForm, self).clean()
        return self.cleaned_data

    def clean_username(self):
        """
        This function is required to overwrite an inherited username clean.
        """
        return self.cleaned_data['username']

    def val_for(self, field_name):
        return raw_value(self, field_name) or None

    def generate_username(self, email):
        localpart = email.split('@', 1)[0][:25]
        c = get_user_model().objects.filter(username__startswith=localpart).count()
        if c > 0:
            localpart += str(c + 1)
        return localpart


class MinLengthPasswordChangeForm(PasswordChangeForm):

    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        validators=[validate_password]
    )


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label=_("Email"))


class UserForm(ModelForm):
    email = forms.EmailField(label=_(u'Email'), required=True)

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(ModelForm):
    country = forms.ModelChoiceField(
        label=_(u'Country'),
        empty_label=_(u'Country'),
        queryset=Country.objects.all(),
    )
    province = forms.ModelChoiceField(
        label=_(u'Province'),
        empty_label=_(u'Province'),
        queryset=Province.objects.all()
    )
    city = forms.ModelChoiceField(
        label=_(u'City'),
        empty_label=_(u'City'),
        queryset=None
    )
    birthday = forms.DateField(
        ('%d/%m/%Y', '%Y-%m-%d'),
        widget=forms.DateInput(attrs={'autocomplete': 'off'}),
        label=_('Birthday')
    )

    def __init__(self, *args, **kw):
        super(ProfileForm, self).__init__(*args, **kw)
        country_id = val_for(self, 'country')
        self.fields['province'].queryset = Province.objects.filter(
            country__id=country_id
        ).all()
        province_id = val_for(self, 'province')
        self.fields['city'].queryset = City.objects.filter(
            province__id=province_id
        ).all()

    class Meta:
        model = UserProfile
        fields = ('city', 'province', 'country', 'birthday', 'gender', 'phone',
                  'avatar')


class UploadAvatarForm(ModelForm):

    avatar = ProcessedImageField(spec_id='users:userprofile:avatar',
                                 processors=[ResizeToFill(100, 100)],
                                 format='JPEG', validators=[validate_size])

    class Meta:
        model = UserProfile
        fields = ('avatar',)


class UploadLogoForm(ModelForm):

    logo = ProcessedImageField(spec_id='companies:company:logo',
                               processors=[ResizeToFill(100, 100)],
                               format='JPEG', validators=[validate_size])

    class Meta:
        model = Company
        fields = ('logo',)

panoplic/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.contrib.sites.requests import RequestSite
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, FormView

from registration import signals
from registration.models import RegistrationProfile
from registration.views import RegistrationView

from companies.models import Company
from search.models import Search
from search.forms import SearchForm
from utils.views import LoginRequiredMixin
from .models import UserProfile
from .forms import (
    ProfileForm, UserForm, CustomRegistrationForm, UploadAvatarForm,
    MinLengthPasswordChangeForm
)


class CustomRegistrationView(RegistrationView):

    form_class = CustomRegistrationForm

    def register(self, form):
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']

        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(self.request)

        user = RegistrationProfile.objects.create_inactive_user(
            site,
            send_email=False,
            username=username,
            email=email,
            password=password,
        )
        signals.user_registered.send(sender=self.__class__, user=user,
                                     request=self.request)

        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        profile = UserProfile(user=user)
        profile.country = form.cleaned_data['country']
        profile.province = form.cleaned_data['province']
        profile.save()

        self.send_activation_email(site, user)

    def send_activation_email(self, site, user):
        """Send the activation mail"""
        profile = RegistrationProfile.objects.get(user=user)
        context_dict = {
            'activation_key': profile.activation_key,
            'expiration_days': settings.ACCOUNT_ACTIVATION_DAYS,
            'site': site,
            'user': user,
            'STATIC_URL': settings.STATIC_URL,
        }
        message = render_to_string('email_templates/activation_email.txt', context_dict)
        html_message = render_to_string('email_templates/activation_email.html', context_dict)
        send_mail(
            'Activar su cuenta',
            message=message,
            html_message=html_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=True,
        )

    def get_success_url(self, user=None):
        """
        Return the name of the URL to redirect to after successful
        user registration.
        """
        return ('registration_complete', (), {})

    def registration_allowed(self):
        return not self.request.user.is_authenticated()


class ProfileView(DetailView):
    """Display the user's profile."""

    model = UserProfile
    context_object_name = 'profile'
    template_name = 'profile.html'


@login_required
def profile_edit(request):
    """This view serves and validates a user profile form."""
    profile = request.user.profile

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=profile)
        user_form = UserForm(request.POST, instance=profile.user)
        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.add_message(request, messages.INFO, _('Profile saved.'))
    else:
        profile_form = ProfileForm(instance=profile)
        user_form = UserForm(instance=request.user)

    return render(request, 'profile_edit.html', {
        'profile_form': profile_form,
        'user_form': user_form,
        'avatar': profile.avatar,
        'favorites': profile.favorites,
        'searches': profile.searches
    })


@login_required
def save_search(request):
    """
    Save a search into the user's profile.
    """
    form = SearchForm(request.GET)
    if form.is_valid():
        search = form.save()
        profile = UserProfile.objects.get(user=request.user)
        profile.searches.add(search)
        profile.save()
        messages.add_message(request, messages.INFO, _('Search saved.'))
        return HttpResponseRedirect(search.get_absolute_url())


def remove_search(request, id):
    """
    Remove a search from the user's profile.
    """
    profile = UserProfile.objects.get(user__pk=request.user.id)
    search = Search.objects.get(pk=id)
    profile.searches.remove(search)
    return HttpResponseRedirect(reverse('edit_profile'))


def favorite(request, id):
    """
    This view adds a company to user favorites.
    """
    profile = UserProfile.objects.get(user__pk=request.user.id)
    company = Company.objects.get(pk=id)
    profile.favorites.add(company)
    return HttpResponseRedirect(reverse('company_view', args=(company.id, slugify(company.name))))


def unfavorite(request, id):
    """
    This view removes a company from user favorites.
    """
    profile = UserProfile.objects.get(user__pk=request.user.id)
    company = Company.objects.get(pk=id)
    profile.favorites.remove(company)
    return HttpResponseRedirect(reverse('profile'))


class PasswordChangeView(LoginRequiredMixin, FormView):

    template_name = 'registration/password_change.html'
    form_class = MinLengthPasswordChangeForm

    def get_success_url(self):
        return reverse('profile', args=(self.request.user.pk,))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        messages.success(self.request,
                         _("Su contraseña ha sido cambiada exitosamente."))
        update_session_auth_hash(self.request, form.user)
        return super().form_valid(form)


def upload_avatar(request):
    """
    This view handles the avatar upload request.
    """
    profile = UserProfile.objects.get(user__pk=request.user.id)
    if request.method == 'POST':
        form = UploadAvatarForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
        else:
            [messages.add_message(request, messages.ERROR, error.as_text()) for
             field, error in form.errors.items()]
    return HttpResponseRedirect(reverse('edit_profile'))


def delete_avatar(request):
    """
    This view handles the avatar deletion request.
    """
    profile = UserProfile.objects.get(user__pk=request.user.id)
    profile.avatar = profile.avatar.field.default
    profile.save()
    return HttpResponseRedirect(reverse('edit_profile'))

panoplic/users/templates/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load guide_extras %}
{% load staticfiles %}

{% block title %}{{ block.super }} | {% trans "Perfil" %}{% endblock %}

{% block include_css_headers %}
<link type="text/css" href="{% static 'css/edicion-perfil.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="body" id="perfil_usuario"> 
   	<header>
		<section class="jumbotron">
			<div class="container">
				<h2>Perfil</h2><h2 class="second_tit">Usuario</h2>
			</div>
			<p class="subtitulo">{% trans 'Visualizá y editá tus datos personales' %}</p>
		</section>
	</header>
   
    <section class="container">
        <div class="row contenido">
            <article id="col_central" class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                {% if user.is_authenticated and user == profile.user %}
                <h3 class="titulo_section">{% trans 'Así ve el resto de los usuarios tu perfil público' %}</h3>
                {% endif %}
                <div class="row datos-perfil">
               		<div class="col-md-12">
    					<div class="mi-info"><div id="avatar" class="mi-avatar">
    						<img src="{{ MEDIA_URL }}{{ profile.avatar }}" class="img-circle">
    					</div>
    					<ul class="mis-datos">
    						<li class="mi-nombre">
    							{{ profile.user.first_name|default:"" }} {{ profile.user.last_name|default:"" }}
    						</li>
    						<li>{{ profile.user.email }}</li>
    						<li>{{ profile.city|default:"" }} ( {{ profile.province|default:"" }} | {{ profile.country }} )</p></li>
    						<li>{{ profile.birthday|default:"" }}</li>
    						<li>{{ profile.get_gender_display }}</li></p>
    					</ul> 
    					</div>
    					{% if user.is_authenticated and user == profile.user %}
    					 <div class="mis-links">
    						<a href="{% url 'edit_profile' %}" class="btn btn-danger btn-sm">{% trans "Editar mis datos" %}</a>
    						<a href="{% url 'password_change' %}" class="btn btn-danger btn-sm">{% trans "Editar contraseña" %}</a>
    					</div>
    					{% endif %}
       				</div>
   			    </div>
  			  <div class="row">  
  				              
		        {% if user.is_authenticated and user == profile.user %}
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="mis-busquedas">             
                        <i class="fa fa-th-list nocircle"></i>
                        <h5>Mis b&uacute;squedas</h5>
                        {% for search in profile.searches.all %}
                        <div class="resultados_fav inside_bloque">                    
                            <a href="{{ search.get_absolute_url }}">
                                <span class="fav_nombre">{{ search.name }}</span>
                            </a> | 
                            <a href="{% url 'remove_search' search.id %}" class="link fav_elimina">eliminar</a>
                            <br>
                            <span class="fav_cat">{{ search.companies_text }}</span> - 
                            <span class="fav_barrio">{{ search.places_text }}</span>
                        </div>
                        {% endfor %}
                    </div>  
                </div>   
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="mis-favoritos">
						<i class="fa fa-heart nocircle"></i>
						<h5>Mis favoritos </h5>
						{% for favorite in profile.favorites.all %}
						<div class="resultados_fav inside_bloque">
							<a href="{% url 'company_view' favorite.id favorite.name|slugify %}">
								<span class="fav_nombre">{{ favorite.name }}</span>
							</a> | 
							<a class="link fav_elimina" href="{% url 'unfavorite' favorite.id %}">eliminar</a>
							<br>
							<span class="fav_cat">{{ favorite.category }}</span> - 
							<span class="fav_barrio">{{ favorite.city }}</span>
						{% endfor %}
						</div> 
					</div>
					{% endif %}
         			</div>
            	</div>
    		</article>
    	</div> 	
    </section>
</div>
{% endblock %}

panoplic/users/templates/profile_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load guide_extras %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}{{ block.super }} | {% trans "Edición de perfil" %}{% endblock %}

{% block include_css_headers %}
<link type="text/css" href="{% static 'css/edicion-perfil.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="body" id="perfil_usuario"> 
   	<header>
		<section class="jumbotron">
			<div class="container">
				<h2>Perfil</h2><h2 class="second_tit">Usuario</h2>
			</div>
			<p class="subtitulo">
          {% trans 'Controlá, visualizá y editá la información de tu cuenta' %}
      </p>
		</section>
	</header>
    <section class="container">
    	<div class="row contenido">
        	<h3 class="titulo_section col-md-12">{% trans 'Modificá los datos registrados de tu cuenta' %}</h3>
		<aside id="col_der" class="col-md-4 col-sm-5 col-md-push-8 col-sm-push-7">
   		<div class="text-center">
   			<a class="btn btn-primary btn-sm" href="{% url 'profile' user.profile.pk %}">
          {% trans 'Ver mi perfil público' %}
        </a>
		    <a class="btn btn-primary btn-sm" href="{% url 'password_change' %}">
          {% trans 'Cambiar contraseña' %}
        </a>
			</div>
   		<br>
			<div id="avatar" class="bloque aqualine">
				<i class="fa fa-user nocircle"></i>
				<h5>Foto de perfil</h5>
				{% include "partial/avatar.html" with id="avatar" div_id="foto_usr" avatar_path=avatar upload_action="/upload_avatar/" delete_action="/delete_avatar" %}
			</div>    
			<div class="bloque aqualine">               
				<i class="fa fa-th-list nocircle"></i>
				<h5>Mis b&uacute;squedas  </h5>
				{% for search in searches.all %}
				  <div class="resultados_fav inside_bloque">                    
					  <a href="{{ search.get_absolute_url }}"><span class="fav_nombre">{{ search.name }}</span></a> | 
            <a href="{% url 'remove_search' search.id %}" class="link fav_elimina">eliminar</a>
				  </div> 
			  {% endfor %}
			</div>        
			<div class="bloque aqualine">
				<i class="fa fa-heart nocircle"></i>
				<h5>Mis favoritos </h5>
				{% for favorite in favorites.all %}
				<div class="resultados_fav inside_bloque">
					<span class="fav_nombre">
					<a href="{% url 'company_view' favorite.id favorite.name|slugify %}" class="link">
						{{ favorite.name }}</a> | 
						<a class="link fav_elimina" href="{% url 'unfavorite' favorite.id %}">
						eliminar
						</a>
					</span>
					<br>
					<span class="fav_cat">{{ favorite.category }}</span> - 
					<span class="fav_barrio">{{ favorite.city }}</span>
				</div>
				{% endfor %}
			</div>   			
		</aside>
		<article id="col_izq" class="col-line col-md-8 col-sm-7 col-md-pull-4 col-sm-pull-5">
            <form action="." method="POST" id="form">
                {% csrf_token %}
                {{ profile_form.non_field_errors }}
                {{ user_form.non_field_errors }}
                <div id="desc" class="bloque">
                   	<h5 class="dato">{% trans 'Datos Públicos' %}</h5>
                    <div class="form_line medio_uno">
                        <label>Nombre</label>
                        {% render_field user_form.first_name class="form-control" %}
                        {{ user_form.first_name.errors }}
                    </div>			
            
                    <div class="form_line medio_dos">
                        <label>Apellido</label>
                        {% render_field user_form.last_name class="form-control" %}
                        {{ user_form.last_name.errors }}
                    </div>            
                            
                    <div class="form_line medio_uno">
                        <label>País</label>
                        {% render_field profile_form.country class="form-control" %}
                        {{ profile_form.country.errors }}
                    </div>
                         
                    <div class="form_line medio_dos">
                       <label>Provincia</label>
                        {% render_field profile_form.province class="form-control" %}
                        {{ profile_form.province.errors }}
                    </div>
                   
                    <div class="form_line medio_uno">
                       <label>Ciudad</label>
                        {% render_field profile_form.city class="form-control"  %}
                        {{ profile_form.city.errors }}
                    </div>

                  	<br>
                   	<h5 class="dato">{% trans 'Datos Privados' %}</h5>
                    <div class="form_line">
                        <label>E-mail</label>
                        {% render_field user_form.email class="form-control" %}
                        {{ user_form.email.errors }}
                    </div>
  
                    <div class="form_line medio_uno">
                        <label>Fecha nacimiento</label>
                        {% render_field profile_form.birthday class="form-control" %}
                        {{ profile_form.birthday.errors }}
                    </div>

                    <div class="form_line medio_dos">
                        <label>Género</label>
                        {% render_field profile_form.gender class="form-control" %}
                        {{ profile_form.gender.errors }}
                    </div>             
           		</div>
                <div id="save">
                    <input type="submit" value="{% trans 'Guardar' %}" class="btn btn-danger"/>
				</div>
            </form>
		</article>   
		</div>
    </section>
</div>
{% endblock %}